defaults:
  - path_config: default
  - model/generator: unet
  - model/discriminator: patch_gan
  - train: default
  - data: default
  - wandb: default
  - inference: default
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  run:
    # dir: ${path_config.base_working_dir}/${path_config.project_name}/working_dir/${path_config.dataset}/runs/${now:%Y-%m-%d_%H-%M-%S}
    dir: ${path_config.base_working_dir}/${path_config.project_name}/working_dir/${path_config.dataset}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    # dir: ${path_config.base_working_dir}/${path_config.project_name}/working_dir/${path_config.dataset}/sweeps/${now:%Y-%m-%d_%H-%M-%S}
    dir: ${path_config.base_working_dir}/${path_config.project_name}/working_dir/${path_config.dataset}/sweeps/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}