name: unet
in_channels: 2  # 1: magnitude, 2: speed
out_channels: 1  # Single channel output (cine)
channels: [32, 64, 128, 256]  # Number of channels in each layer
strides: [2, 2, 2]  # Stride for each downsampling layer
num_res_units: 0  # Number of residual units in each block
activation: "PReLU"  # Activation function

--------loss weights------------------------------------------------------------------------------------------------
weights:
  gan: 1.0  # Weight for GAN loss
  l1: 100.0  # Weight for L1 loss
  ssim: 1.0  # Weight for SSIM loss

# optimizer parameters------------------------------------------------------------------------------------------------
optimizer:
  name: "Adam"
  lr: 0.0002 # Learning rate
  betas: [0.5, 0.999] # Beta1 and beta2 for Adam optimizer