# Debug parameters------------------------------------------------------------------------------------------------

debug: false  # Enable debug logging

# Data parameters------------------------------------------------------------------------------------------------

# patch parameters
patch_size: [48, 48, 48]  # Size of 3D patches for training
patch_overlap: 0  # Overlap between patches for inference (can be 0 for no overlap)
patch_aggregation_overlap_mode: "hann"  # Mode for patch overlap (can be "crop" or "hann" or "average")

# queue parameters
queue_length: 1000  # Length of the patch queue
samples_per_volume: 8  # Number of patches to sample per volume
num_queue_workers: 8  # Number of workers for patch sampling
num_loader_workers: 0  # Number of workers for data loading
shuffle_subjects: true  # Shuffle subjects in the dataset
shuffle_patches: true  # Shuffle patches in the queue
pin_memory: true  # Pin memory for faster data transfer
timepoints_as_augmentation: true  # Whether to use timepoints as augmentation

# training parameters------------------------------------------------------------------------------------------------

batch_size: 32  # Batch size for training
num_epochs: 1000  # Number of training epochs
generator_lr: 0.0002  # Learning rate
discriminator_lr: 0.00005  # Learning rate
lambda_l1: 100.0  # Weight for L1 loss
lambda_ssim: 5.0  # Weight for SSIM loss

# validation, checkpointing, and early stopping parameters------------------------------------------------------------------------------------------------
discriminator_update_threshold: 0  # Threshold for discriminator update. 0 means update every batch.
num_sample_predictions: -1  # Number of sample predictions for visualization. -1 means all subjects.
early_stop_patience: 200  # Number of epochs to wait before early stopping
validation_time_index: 0  # Time index for validation
visualization_interval: 10  # Save visualization every n epochs
checkpoint_interval: 10  # Save checkpoint every n epochs

# augmentation parameters------------------------------------------------------------------------------------------------

# Peak systolic velocity only
peak_systolic_only: true  # Whether to use peak systolic only

# Elastic deformation
num_control_points: 10  # Number of control points for elastic deformation
max_displacement: 25  # Maximum displacement for elastic deformation
elastic_deformation_probability: 1  # Probability of applying elastic deformation