patch_size: [96, 96, 96]  # Size of 3D patches for training
queue_length: 100  # Length of the patch queue
samples_per_volume: 8  # Number of patches to sample per volume
num_queue_workers: 4  # Number of workers for patch sampling
num_loader_workers: 0  # Number of workers for data loading
batch_size: 24  # Batch size for training
lr: 0.0002  # Learning rate
num_epochs: 200  # Number of training epochs
lambda_l1: 100.0  # Weight for L1 loss
shuffle_subjects: true  # Shuffle subjects in the dataset
shuffle_patches: true  # Shuffle patches in the queue
pin_memory: true  # Pin memory for faster data transfer
debug: false  # Enable debug logging