#!/bin/bash
# Transfer missing -1 folders (4D flow data) from bastion to fourier
# Run this on bastion

SRC="/media/evmasuta/hdd/cardiac-ucsd-mr-exams"
DST="/home/ayeluru/mnt/fourier/repository/vascular-superenhancement-4d-flow/all_patients/unzipped_files"

# 121 patients to transfer
PATIENTS=(
    "Ackdradum"
    "Baluedoog"
    "Baquague"
    "Batamom"
    "Betipha"
    "Bopayep"
    "Bumaban"
    "Buquatie"
    "Clafufi"
    "Coyrimuf"
    "Datiploo"
    "Dufehi"
    "Dukivi"
    "Enbrounkush"
    "Erimor"
    "Esuckood"
    "Eyiyub"
    "Fajupo"
    "Fameba"
    "Fodosni"
    "Gadefa"
    "Gepebet"
    "Gesoubu"
    "Giruca"
    "Gitackas"
    "Gizumom"
    "Goquogi"
    "Gotedol"
    "Grinafru"
    "Gririeyoze"
    "Guedocham"
    "Gukrapen"
    "Gupimug"
    "Haboutoth"
    "Heenknuepan"
    "Hejinup"
    "Hesgolnim"
    "Heyatam"
    "Houguba"
    "Hustesooch"
    "Incepey"
    "Jafuju"
    "Jahadoy"
    "Jeefukfoy"
    "Jethogu"
    "Jibliqui"
    "Jolanu"
    "Juhogtod"
    "Klenosis"
    "Kobese"
    "Kotookot"
    "Lamiemmos"
    "Larefier"
    "Leerscoopub"
    "Lestrafi"
    "Leyirous"
    "Lulafak"
    "Mabaydem"
    "Mibago"
    "Miquegop"
    "Modager"
    "Moogbuley"
    "Mosomu"
    "Muedelig"
    "Mujaley"
    "Nafbugad"
    "Naliten"
    "Nayeboy"
    "Necegeb"
    "Nedousu"
    "Nemaho"
    "Netaklay"
    "Nimotsuer"
    "Niritha"
    "Nitheci"
    "Nosatof"
    "Nusyeb"
    "Onetom"
    "Ornakash"
    "Pekafe"
    "Pidobaf"
    "Pifima"
    "Pigusnof"
    "Pikcelak"
    "Pisunklorn"
    "Potrostri"
    "Prusrabi"
    "Pufasiey"
    "Quebida"
    "Quebike"
    "Quegazer"
    "Quereyos"
    "Queyieckliep"
    "Quibloyag"
    "Quimafbray"
    "Quotooyuk"
    "Rebipu"
    "Rilulu"
    "Rodepit"
    "Rofuzor"
    "Salabo"
    "Scekoogar"
    "Shelufi"
    "Shidunu"
    "Siprueque"
    "Siquojie"
    "Snubroset"
    "Sosaquo"
    "Stepagok"
    "Stomurquos"
    "Thigruhi"
    "Tijune"
    "Tijupro"
    "Turndernize"
    "Ubupneg"
    "Ufochux"
    "Ukdomor"
    "Usstanon"
    "Usuegtug"
    "Vabriraf"
    "Yocijuk"
)

TOTAL=${#PATIENTS[@]}
COUNT=0
FAILED=0

for PATIENT in "${PATIENTS[@]}"; do
    COUNT=$((COUNT + 1))
    echo "[$COUNT/$TOTAL] Transferring $PATIENT-1 -> $DST/$PATIENT/"
    rsync -a "$SRC/$PATIENT-1/" "$DST/$PATIENT/" 2>&1
    if [ $? -ne 0 ]; then
        echo "  ERROR: Failed to transfer $PATIENT"
        FAILED=$((FAILED + 1))
    fi
done

echo ""
echo "Transfer complete: $((TOTAL - FAILED))/$TOTAL succeeded, $FAILED failed"
