inference_name: senate
checkpoint_path: /home/ayeluru/vascular-superenhancement-4d-flow/working_dir/all_patients/runs/2025-07-31/08-26-11/best_checkpoints/epoch_0623.pt
output_dir: ${path_config.base_working_dir}/${path_config.project_name}/working_dir/inference/${inference.inference_name}
patch_size: [48, 48, 48]
patch_overlap: 20
patch_aggregation_overlap_mode: "hann"
num_workers: 1
batch_size: 200

# Patient parameters for inference
patient_id: null  # Will be overridden from command line
time_point: 3     # Default time point, can be overridden